"""cdrdao TOC file parser (CD-DA only).

Parses .toc files generated by cdrdao and extracts disc and track information.
Only CD-DA (Audio CD) is supported.
"""

import re
from dataclasses import dataclass, field
from pathlib import Path

# CD-DA constants
FRAMES_PER_SECOND = 75
BYTES_PER_FRAME = 2352  # 44100Hz × 16bit × 2ch ÷ 75fps


def _frames_to_msf(total_frames: int) -> tuple[int, int, int]:
    """Convert total frames to (minutes, seconds, frames)."""
    if total_frames < 0:
        raise ValueError("total_frames must be non-negative")
    total_seconds, frames = divmod(total_frames, FRAMES_PER_SECOND)
    minutes, seconds = divmod(total_seconds, 60)
    return minutes, seconds, frames


@dataclass
class MSF:
    """MSF (Minutes:Seconds:Frames) time representation (1 second = 75 frames)."""

    minutes: int
    seconds: int
    frames: int

    def __post_init__(self) -> None:
        self._normalize()

    def _normalize(self) -> None:
        """Normalize values (handle overflow)."""
        m, s, f = _frames_to_msf(self.to_frames())
        self.minutes, self.seconds, self.frames = m, s, f

    def to_frames(self) -> int:
        """Convert to total frames."""
        return (self.minutes * 60 + self.seconds) * FRAMES_PER_SECOND + self.frames

    def to_seconds(self) -> float:
        """Convert to seconds."""
        return self.to_frames() / FRAMES_PER_SECOND

    def to_bytes(self) -> int:
        """Convert to byte offset."""
        return self.to_frames() * BYTES_PER_FRAME

    @classmethod
    def from_string(cls, msf_string: str) -> MSF:
        """Create an MSF instance from a string.

        Args:
            msf_string: "MM:SS:FF" format string, or "0"
        """
        s = msf_string.strip()
        if s == "0":
            return cls(0, 0, 0)

        parts = s.split(":")
        if len(parts) != 3:
            raise ValueError(f"Invalid MSF format: {msf_string}")

        return cls(int(parts[0]), int(parts[1]), int(parts[2]))

    @classmethod
    def from_frames(cls, total_frames: int) -> MSF:
        """Create an MSF instance from total frames."""
        m, s, f = _frames_to_msf(total_frames)
        return cls(m, s, f)

    def __str__(self) -> str:
        return f"{self.minutes:02d}:{self.seconds:02d}:{self.frames:02d}"

    def __repr__(self) -> str:
        return f"MSF({self.minutes}, {self.seconds}, {self.frames})"

    def __add__(self, other: MSF) -> MSF:
        return MSF.from_frames(self.to_frames() + other.to_frames())

    def __sub__(self, other: MSF) -> MSF:
        result = self.to_frames() - other.to_frames()
        if result < 0:
            raise ValueError("Result would be negative")
        return MSF.from_frames(result)


@dataclass
class Track:
    """Audio track information."""

    track_number: int
    file_name: str
    file_offset: MSF  # Start position within the bin file
    length: MSF  # Track length
    isrc: str | None = None
    pregap: MSF | None = None  # Pregap length (from START)

    @property
    def file_end_offset(self) -> MSF:
        """End position within the bin file."""
        return self.file_offset + self.length

    @property
    def audio_start_offset(self) -> MSF:
        """Actual audio start offset (excluding pregap)."""
        return (
            self.file_offset
            if self.pregap is None
            else (self.file_offset + self.pregap)
        )

    @property
    def audio_length(self) -> MSF:
        """Actual audio length (excluding pregap)."""
        return self.length if self.pregap is None else (self.length - self.pregap)


@dataclass
class TOC:
    """CD-DA TOC (Table of Contents) information."""

    catalog: str | None = None  # MCN/UPC
    tracks: list[Track] = field(default_factory=list)

    @property
    def track_count(self) -> int:
        return len(self.tracks)

    @property
    def total_length(self) -> MSF | None:
        if not self.tracks:
            return None
        last = self.tracks[-1]
        return last.file_offset + last.length

    @property
    def bin_file(self) -> str | None:
        if not self.tracks:
            return None
        return self.tracks[0].file_name

    def get_track(self, track_number: int) -> Track | None:
        """Get a track by its number (1-based)."""
        return next((t for t in self.tracks if t.track_number == track_number), None)


# Regex patterns
_RE_CATALOG = re.compile(r'^CATALOG\s+"([^"]+)"')
_RE_ISRC = re.compile(r'^ISRC\s+"([^"]+)"')
_RE_FILE = re.compile(r'^FILE\s+"([^"]+)"\s+(\S+)\s+(\S+)')
_RE_START = re.compile(r"^START\s+(\S+)")

# Lines to ignore
_IGNORE_LINES = frozenset(
    [
        "CD_DA",
        "NO COPY",
        "COPY",
        "NO PRE_EMPHASIS",
        "TWO_CHANNEL_AUDIO",
    ]
)


def _iter_effective_lines(content: str):
    """Yield normalized, relevant lines."""
    for raw in content.splitlines():
        line = raw.strip()
        if not line or line.startswith("//") or line in _IGNORE_LINES:
            continue
        yield line


def parse_string(content: str) -> TOC:
    """Parse TOC content and return a TOC object."""
    _toc = TOC()
    track_number = 0
    current_isrc: str | None = None
    current_file: tuple[str, MSF, MSF] | None = None
    current_start: MSF | None = None

    def flush_track() -> None:
        nonlocal current_isrc, current_file, current_start
        if current_file is not None:
            _toc.tracks.append(
                Track(
                    track_number=track_number,
                    file_name=current_file[0],
                    file_offset=current_file[1],
                    length=current_file[2],
                    isrc=current_isrc,
                    pregap=current_start,
                )
            )
        current_isrc = None
        current_file = None
        current_start = None

    for line in _iter_effective_lines(content):
        if match := _RE_CATALOG.match(line):
            _toc.catalog = match.group(1)
            continue

        if line == "TRACK AUDIO":
            flush_track()
            track_number += 1
            continue

        if match := _RE_ISRC.match(line):
            current_isrc = match.group(1)
            continue

        if match := _RE_FILE.match(line):
            current_file = (
                match.group(1),
                MSF.from_string(match.group(2)),
                MSF.from_string(match.group(3)),
            )
            continue

        if match := _RE_START.match(line):
            current_start = MSF.from_string(match.group(1))
            continue

    flush_track()
    return _toc


def parse_file(file_path: str | Path, encoding: str = "utf-8") -> TOC:
    """Parse a TOC file and return a TOC object."""
    path = Path(file_path)
    return parse_string(path.read_text(encoding=encoding))


def parse_toc(file_path: str | Path) -> TOC:
    """Parse a TOC file (compatibility wrapper)."""
    return parse_file(file_path)


def parse_toc_string(content: str) -> TOC:
    """Parse TOC content (compatibility wrapper)."""
    return parse_string(content)


# ===== Manual test code =====
if __name__ == "__main__":
    tocs_dir = Path(__file__).parent / "tocs"

    if tocs_dir.exists():
        print("=" * 60)
        print("CDRDAO TOC Parser test (CD-DA only)")
        print("=" * 60)

        for toc_file in sorted(tocs_dir.glob("*.toc")):
            print(f"\n--- {toc_file.name} ---")

            try:
                toc = parse_toc(toc_file)

                if toc.catalog:
                    print(f"Catalog: {toc.catalog}")
                print(f"Track count: {toc.track_count}")
                print(f"Total length: {toc.total_length}")
                print(f"Bin file: {toc.bin_file}")

                print("\nTracks:")
                for track in toc.tracks:
                    pregap_info = f" (pregap: {track.pregap})" if track.pregap else ""
                    print(
                        f"  Track {track.track_number:2d}: "
                        f"{track.file_offset} - {track.length} "
                        f"[{track.audio_length}]{pregap_info}"
                    )
                    if track.isrc:
                        print(f"            ISRC: {track.isrc}")

            except Exception as e:
                print(f"Error: {e}")
                import traceback

                traceback.print_exc()
    else:
        print(f"tocs directory not found: {tocs_dir}")
